#!/bin/sh
## add_to_lib.sh for add_to_lib in /home/ungaro_l/myscripts
## 
## Made by Luca Ungaro
## Login   <ungaro_l@epitech.net>
## 
## Started on  Sun Oct  4 14:45:05 2015 Luca Ungaro
## Last update Mon Nov  9 10:39:10 2015 Luca Ungaro
##

$LIBPATH=$HOME/mylibs/lib/my/

if [ $# -ge 1 ]
then
    if [ $1 = "-h" ] || [ $1 = "-info" ]
    then
	echo -e "Script to add a c source file to default personnal library, e.c. libmy.a (wich is used for compiling with lcc)\n\nUsage : add_to_lib source_file.c [other_source_files.c\nlibmyc.a and all releaving source/objects files are located at $LIBPATH]"
    else
	cp $@ $LIBPATH;				$HOME/myscripts/my_defile_letters "Transferring source files..." 1000; echo ""
	make -C $LIBPATH
	echo -e "\n------------------------------------\n\tIF EVERYTHING WENT RIGHT,\n\tDON'T FORGOT THE HEADERS !\n------------------------------------"

	# OLD WAY
	# rm $HOME/mylibs/sources/*.o; rm $HOME/mylibs/sources/*.gch
	# gcc -c $HOME/mylibs/sources/*;				$HOME/myscripts/my_defile_letters "Compiling..." 1000; echo ""
	# rm $HOME/mylibs/objects/*
	# mv *.o $HOME/mylibs/objects;				$HOME/myscripts/my_defile_letters "Getting object files..." 1000; echo ""
	# ar rc $HOME/mylibs/libmy.a $HOME/mylibs/objects/*;	$HOME/myscripts/my_defile_letters "Packaging library : /home/ungaro_l/mylibs/libmyc.a" 1000; echo ""
	# ranlib $HOME/mylibs/libmy.a;				$HOME/myscripts/my_defile_letters "Indexing libmy.a..." 1000; echo ""
	# $HOME/myscripts/my_defile_letters "Done !" 1000; echo ""
    fi
else
    echo"Usage : add_to_lib source_file.c [other_source_files.c]"
fi
