#!/bin/sh
## lcc.sh for lib-compile in /home/ungaro_l/myscripts
## 
## Made by Luca Ungaro
## Login   <ungaro_l@epitech.net>
## 
## Started on  Sun Oct  4 12:50:12 2015 Luca Ungaro
## Last update Mon Nov  9 10:32:19 2015 Luca Ungaro
##


##	Customize the lib down here !

LIBPATH=$HOME/mylibs/lib
LIBNAME=my			# Corresponding to [lib]my[.a]
INCLUDE=$HOME/mylibs/include
CFLAGS="-W -Wall -Wextra -Werrors -ansi"

##	Compiling script

if [ $# -ge 1 ]
then
    if [ $1 = "-h" ] || [ $1 = '-info' ]
    then
	echo -e "Auto-compiler with cc, wich :\n\tAllows auto-completion with tab typing\n\tAuto-compiles all .c files if none specified\n\tUses ~/mylibs/lib/libmyc.a as additional library\n\nUsage : lcc main_file.c [other_files.c]\tfor manual compiling\n\tlcc [void]\t\t\tfor auto-compiling ./*.c"
    else
	gcc $@ -L$LIBPATH -l$LIBNAME -I$INCLUDE
    fi
else
    gcc *.c -L$LIBPATH -l$LIBNAME -I$INCLUDE
fi
