#!/bin/sh
## lcc.sh for lib-compile in /home/ungaro_l/myscripts
## 
## Made by Luca Ungaro
## Login   <ungaro_l@epitech.net>
## 
## Started on  Sun Oct  4 12:50:12 2015 Luca Ungaro
## Last update Fri Jan  8 11:26:03 2016 Luca Ungaro
##


##	Customize the lib down here !

CFLAGS="-W -Wall -Wextra -Werror -ansi -pedantic"
LIBLAPIN="-L$HOME/.froot/lib/ -llapin -lsfml-audio -lsfml-graphics -lsfml-window -lsfml-system -lstdc++ -ldl -lm"
LIBMY="-L$HOME/mylibs/lib/ -lmy -I$HOME/mylibs/lib/my/include"

##	Compiling script

if [ $# -ge 1 ]
then
    if [ $1 = "-h" ] || [ $1 = '-info' ]
    then
	echo -e "Auto-compiler with Liblapin and gcc, wich :\n\tAllows auto-completion with tab typing\n\tAuto-compiles all .c files if none specified\n\tUses ~/mylibs/libmyc.a  and the LibLapin as additional library\n\nUsage : lcc main_file.c [other_files.c]\tfor manual compiling\n\tlcc [void]\t\t\tfor auto-compiling ./*.c"
    else
	gcc $@ $LIBLAPIN $LIBMY ##$CFLAGS
    fi
else
    gcc *.c $LIBLAPIN $LIBMY ##$CFLAGS
fi
