#!/bin/sh
## push_that.sh for push_that in /home/ungaro_l/rendu/Piscine_C_J02
## 
## Made by Luca Ungaro
## Login   <ungaro_l@epitech.net>
## 
## Started on  Tue Sep 29 15:08:22 2015 Luca Ungaro
## Last update Sat Dec  5 15:28:20 2015 Luca Ungaro
##

make fclean
clean

git add --all
git commit -m "$1"
git push origin master
