#!/bin/sh
## push_that.sh for push_that in /home/ungaro_l/rendu/Piscine_C_J02
## 
## Made by Luca Ungaro
## Login   <ungaro_l@epitech.net>
## 
## Started on  Tue Sep 29 15:08:22 2015 Luca Ungaro
## Last update Thu Feb  4 19:02:36 2016 Luca Ungaro
##

make fclean
clean

git add --all
if [ $# -ge 1 ]
then
    git commit -m "$@"
else
    git commit
fi
git push origin master
